# Site settings
title: 瓠樽
email: dw#watelier.cn
description: "以瓠為樽而浮乎江湖"
url: "https://blog.dylanwu.space"
baseurl: ""
username: DylanWu
# disqus_shortname: your_shortname
repository: wuzhongyi1105/wuzhongyi1105.github.io
github_url: https://github.com/wuzhongyi1105/wuzhongyi1105.github.io

# SEO
twitter:
  username: wuzhongyi1105
  card: summary
logo: /assets/icon/apple-touch-icon-180x180.png
social:
  name: Dylan Wu
  links:
    - https://twitter.com/wuzhongyi1105
    - https://www.facebook.com/wuzhongyi1105
    - https://www.linkedin.com/in/%E4%B8%AD%E9%80%B8-%E5%90%B4-225144109
    - https://github.com/wuzhongyi1105
    - https://www.instagram.com/wuzhongyi1105

gems: [jekyll-paginate, jekyll-sitemap, jekyll-seo-tag, jekyll-mentions, jemoji]

# pagination
paginate: 5

# Build settings
markdown: kramdown
# permalink: pretty

jekyll-mentions:
  base_url: https://twitter.com

defaults:
  - scope:
      path: ""
    values:
      image: /assets/icon/apple-touch-icon-180x180.png