# Site settings
title: 瓠樽
email: dw#watelier.cn
description: "以瓠為樽而浮乎江湖"
url: "https://blog.dylanwu.space"
baseurl: ""
username: DylanWu
disqus_shortname: your_shortname
repository: wuzhongyi1105/wuzhongyi1105.github.io
github_url: https://github.com/wuzhongyi1105/wuzhongyi1105.github.io

gems: [jekyll-paginate, jekyll-sitemap, jekyll-seo-tag, jekyll-mentions, jemoji]

# pagination
paginate: 5

# Build settings
markdown: kramdown
# permalink: pretty
